version: "3.0"

services:
  config-service:
    image: config-service
    ports:
      - "8766:8766"
    networks:
      - ecommerce-network

  registry-server:
    image: registry-server
    ports:
      - "8761:8761"
    networks:
      - ecommerce-network

  user-service:
    restart: always
    image: user-service
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    ports:
      - "8763:8763"
    networks:
      - ecommerce-network
    depends_on:
      - config-service
      - registry-server
  product-service:
    restart: always
    image: product-service
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    ports:
      - "8764:8764"
    networks:
      - ecommerce-network
    depends_on:
      - config-service
      - registry-server
  order-service:
    restart: always
    image: order-service
    environment:
      - SPRING_PROFILES_ACTIVE= docker
    ports:
      - "8765:8765"
    networks:
      - ecommerce-network
    depends_on:
      - config-service
      - registry-server
#  api-gateway:
#    restart: always
#    image: api-gateway
#    environment:
#      - SPRING_PROFILES_ACTIVE= docker
#    ports:
#      - "8768:8768"
#    networks:
#      - ecommerce-network
#    depends_on:
#      - config-service
#      - registry-server
networks:
  ecommerce-network:
    driver: bridge



