spring:
  application:
    name: jwt_practice
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/spring_jwt_sec_tutorial
    password: 14031998
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      show-sql: true
      ddl-auto: create-drop
